### ISSUE TITLE
Where is RStudio saving the files?

### ISSUE THREAD

**Issue by EcologyTom** [paleo13/marxan#20]
Hello,

Thanks for your work on this package! I'm working through the tutorial. For the description about the function 'marxan' you write;
" ...(2) saving the input data to a folder on the computer, (3) copying the MARXAN executable file to that folder, (4) running MARXAN,... "

Where is this taking place? Where are the files saved to? They aren't appearing in my folder for the RStudio Project. I hope this doesn't seem trivial, I want to understand how it is all working.

Many thanks,
Tom

**Comment by paleo13** [comment]
Hi,

By default all the MARXAN runs take place in a temporary directory (run the function `tempdir()` to find it). Note the location of this changes each time you restart R.

If you are calling the solve function (and not the general marxan function), you can change the location of this using the wd argument (eg. `wd=getwd()`). You will also need to specify `clean=FALSE` to prevent R from deleting the files after running MARXAN. 

Let me know if you have any more questions,

Jeff

**Comment by EcologyTom** [comment]
Hi Jeff,

Many thanks. Helps me to understand what's going on. 

Kind regards, Tom
